/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityPost {
  'id' : bigint,
  'likeCount' : bigint,
  'content' : string,
  'displayName' : string,
  'city' : string,
  'author' : Principal,
  'mediaBlob' : [] | [ExternalBlob],
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Issue {
  'id' : bigint,
  'upvotes' : bigint,
  'photoBlob' : [] | [ExternalBlob],
  'title' : string,
  'description' : string,
  'gpsLocation' : string,
  'timestamp' : bigint,
  'category' : IssueCategory,
  'isVigilance' : boolean,
  'reporter' : Principal,
}
export type IssueCategory = { 'healthcare' : null } |
  { 'publicSafety' : null } |
  { 'other' : null } |
  { 'corruption' : null } |
  { 'sanitation' : null } |
  { 'infrastructure' : null };
export interface MarketRates {
  'cng' : string,
  'lpg' : string,
  'onion' : string,
  'petrol' : string,
  'tomato' : string,
  'diesel' : string,
  'potato' : string,
}
export interface News { 'headline' : string, 'timestamp' : bigint }
export interface PrivateMessage {
  'id' : bigint,
  'content' : string,
  'sender' : Principal,
  'mediaBlob' : [] | [ExternalBlob],
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface Status {
  'photoBlob' : [] | [ExternalBlob],
  'content' : string,
  'displayName' : string,
  'city' : string,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface UserProfile {
  'alias' : string,
  'displayName' : string,
  'anonymousMode' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'unlockedCertificate' : boolean,
  'reportsCount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNews' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCommunityPost' : ActorMethod<[string, string, [] | [string]], bigint>,
  'createIssue' : ActorMethod<
    [string, string, IssueCategory, string, [] | [string], boolean],
    bigint
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommunityPostsByCity' : ActorMethod<[string], Array<CommunityPost>>,
  'getConversationHistory' : ActorMethod<[Principal], Array<PrivateMessage>>,
  'getDisplayName' : ActorMethod<[Principal], string>,
  'getMarketRates' : ActorMethod<[], MarketRates>,
  'getNews' : ActorMethod<[], Array<News>>,
  'getPublicIssues' : ActorMethod<[], Array<Issue>>,
  'getStatusesByCity' : ActorMethod<[string], Array<Status>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeCommunityPost' : ActorMethod<[bigint], undefined>,
  'listConversations' : ActorMethod<[], Array<Principal>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendPrivateMessage' : ActorMethod<
    [Principal, string, [] | [string]],
    bigint
  >,
  'setDisplayName' : ActorMethod<[string, boolean], undefined>,
  'setMarketRates' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'setStatus' : ActorMethod<[string, string, [] | [string]], undefined>,
  'upvoteIssue' : ActorMethod<[bigint], undefined>,
  'verifyImage' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];