/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const IssueCategory = IDL.Variant({
  'healthcare' : IDL.Null,
  'publicSafety' : IDL.Null,
  'other' : IDL.Null,
  'corruption' : IDL.Null,
  'sanitation' : IDL.Null,
  'infrastructure' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'alias' : IDL.Text,
  'displayName' : IDL.Text,
  'anonymousMode' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CommunityPost = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'content' : IDL.Text,
  'displayName' : IDL.Text,
  'city' : IDL.Text,
  'author' : IDL.Principal,
  'mediaBlob' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
});
export const PrivateMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'mediaBlob' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const MarketRates = IDL.Record({
  'cng' : IDL.Text,
  'lpg' : IDL.Text,
  'onion' : IDL.Text,
  'petrol' : IDL.Text,
  'tomato' : IDL.Text,
  'diesel' : IDL.Text,
  'potato' : IDL.Text,
});
export const News = IDL.Record({
  'headline' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Issue = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'photoBlob' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'description' : IDL.Text,
  'gpsLocation' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IssueCategory,
  'isVigilance' : IDL.Bool,
  'reporter' : IDL.Principal,
});
export const Status = IDL.Record({
  'photoBlob' : IDL.Opt(ExternalBlob),
  'content' : IDL.Text,
  'displayName' : IDL.Text,
  'city' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const UserStats = IDL.Record({
  'unlockedCertificate' : IDL.Bool,
  'reportsCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNews' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCommunityPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createIssue' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IssueCategory,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityPostsByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(CommunityPost)],
      ['query'],
    ),
  'getConversationHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PrivateMessage)],
      ['query'],
    ),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getMarketRates' : IDL.Func([], [MarketRates], ['query']),
  'getNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
  'getPublicIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
  'getStatusesByCity' : IDL.Func([IDL.Text], [IDL.Vec(Status)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeCommunityPost' : IDL.Func([IDL.Nat], [], []),
  'listConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendPrivateMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'setDisplayName' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'setMarketRates' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'upvoteIssue' : IDL.Func([IDL.Nat], [], []),
  'verifyImage' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const IssueCategory = IDL.Variant({
    'healthcare' : IDL.Null,
    'publicSafety' : IDL.Null,
    'other' : IDL.Null,
    'corruption' : IDL.Null,
    'sanitation' : IDL.Null,
    'infrastructure' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'alias' : IDL.Text,
    'displayName' : IDL.Text,
    'anonymousMode' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CommunityPost = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'content' : IDL.Text,
    'displayName' : IDL.Text,
    'city' : IDL.Text,
    'author' : IDL.Principal,
    'mediaBlob' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
  });
  const PrivateMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'mediaBlob' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const MarketRates = IDL.Record({
    'cng' : IDL.Text,
    'lpg' : IDL.Text,
    'onion' : IDL.Text,
    'petrol' : IDL.Text,
    'tomato' : IDL.Text,
    'diesel' : IDL.Text,
    'potato' : IDL.Text,
  });
  const News = IDL.Record({ 'headline' : IDL.Text, 'timestamp' : IDL.Int });
  const Issue = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'photoBlob' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'description' : IDL.Text,
    'gpsLocation' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IssueCategory,
    'isVigilance' : IDL.Bool,
    'reporter' : IDL.Principal,
  });
  const Status = IDL.Record({
    'photoBlob' : IDL.Opt(ExternalBlob),
    'content' : IDL.Text,
    'displayName' : IDL.Text,
    'city' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const UserStats = IDL.Record({
    'unlockedCertificate' : IDL.Bool,
    'reportsCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNews' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCommunityPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createIssue' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IssueCategory,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityPostsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CommunityPost)],
        ['query'],
      ),
    'getConversationHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PrivateMessage)],
        ['query'],
      ),
    'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getMarketRates' : IDL.Func([], [MarketRates], ['query']),
    'getNews' : IDL.Func([], [IDL.Vec(News)], ['query']),
    'getPublicIssues' : IDL.Func([], [IDL.Vec(Issue)], ['query']),
    'getStatusesByCity' : IDL.Func([IDL.Text], [IDL.Vec(Status)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeCommunityPost' : IDL.Func([IDL.Nat], [], []),
    'listConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendPrivateMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'setDisplayName' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'setMarketRates' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setStatus' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'upvoteIssue' : IDL.Func([IDL.Nat], [], []),
    'verifyImage' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };